In [1]:
import sys
sys.path.append("/mnt/d/PythonPP20/Uti/")
sys.path.append("/mnt/d/PythonPP20/Uti/Uti/")
import xarray as xr
import numpy as np 
import scipy.stats as sts
import Uti.reg as reg
import Uti

In [2]:

np.random.seed(10)
x = np.random.randn(10)
err = np.random.randn(10)*0.5
y = -1.5 * x + 0.6 + err
y = np.repeat(y[np.newaxis,...],axis=0,repeats=16).T
y = y.reshape(10,4,4)
sts.pearsonr(y[:,0,0],x)

(-0.9155802962594594, 0.00020047684816811647)

In [3]:
reg.linear_reg(x,y)

10
(10, 16)


(array([[-1.27514307, -1.27514307, -1.27514307, -1.27514307],
        [-1.27514307, -1.27514307, -1.27514307, -1.27514307],
        [-1.27514307, -1.27514307, -1.27514307, -1.27514307],
        [-1.27514307, -1.27514307, -1.27514307, -1.27514307]]),
 array([[0.67536701, 0.67536701, 0.67536701, 0.67536701],
        [0.67536701, 0.67536701, 0.67536701, 0.67536701],
        [0.67536701, 0.67536701, 0.67536701, 0.67536701],
        [0.67536701, 0.67536701, 0.67536701, 0.67536701]]),
 array([[-0.9155803, -0.9155803, -0.9155803, -0.9155803],
        [-0.9155803, -0.9155803, -0.9155803, -0.9155803],
        [-0.9155803, -0.9155803, -0.9155803, -0.9155803],
        [-0.9155803, -0.9155803, -0.9155803, -0.9155803]]),
 array([[0.00020048, 0.00020048, 0.00020048, 0.00020048],
        [0.00020048, 0.00020048, 0.00020048, 0.00020048],
        [0.00020048, 0.00020048, 0.00020048, 0.00020048],
        [0.00020048, 0.00020048, 0.00020048, 0.00020048]]))

In [4]:
import xarray as xr
Had_loc ="../../DATA/HadISST_sst_2x2.nc"
sst = xr.open_dataset(Had_loc)['sst']
ssta = Uti.GetAnom(sst,method=0)

In [5]:
ssta

<xarray.DataArray 'sst' (time: 1828, lat: 90, lon: 180)>
array([[[         nan,          nan,          nan, ...,          nan,
                  nan,          nan],
        [         nan,          nan,          nan, ...,          nan,
                  nan,          nan],
        [         nan,          nan,          nan, ...,          nan,
                  nan,          nan],
        ...,
        [  45.669262 ,   44.03821  ,  161.47363  , ...,   55.45553  ,
           53.82449  ,   50.562397 ],
        [  71.76599  ,   79.92123  ,   78.29018  , ...,   75.02808  ,
           70.13494  ,   68.5039   ],
        [  45.668762 ,   45.66864  ,   44.037598 , ...,   50.561768 ,
           48.930786 ,   44.037598 ]],

       [[         nan,          nan,          nan, ...,          nan,
                  nan,          nan],
        [         nan,          nan,          nan, ...,          nan,
                  nan,          nan],
        [         nan,          nan,          nan, ...,          nan,
                  nan,          nan],
...
        [ 156.58025  ,  399.60605  ,  -96.2319   , ...,  177.78378  ,
          179.41487  ,  600.22437  ],
        [ -68.50418  , -316.4231   , -565.973    , ..., -233.23962  ,
          -57.087067 ,  -68.50418  ],
        [-185.9397   , -445.27606  , -455.06232  , ..., -433.8587   ,
         -433.85876  , -437.12085  ]],

       [[         nan,          nan,          nan, ...,          nan,
                  nan,          nan],
        [         nan,          nan,          nan, ...,          nan,
                  nan,          nan],
        [         nan,          nan,          nan, ...,          nan,
                  nan,          nan],
        ...,
        [-283.802    , -464.84808  , -707.8739   , ...,   88.07599  ,
           81.5517   ,  572.49646  ],
        [-569.2351   , -574.1283   , -750.2811   , ..., -740.4949   ,
         -742.12585  , -572.49725  ],
        [-192.46387  ,   52.1929   ,   50.56186  , ..., -440.383    ,
         -438.7519   ,   53.823944 ]]], dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 1870-01-16T12:00:00 ... 2022-04-16T12:00:00
  * lon      (lon) float64 0.0 2.0 4.0 6.0 8.0 ... 350.0 352.0 354.0 356.0 358.0
  * lat      (lat) float64 -89.0 -87.0 -85.0 -83.0 -81.0 ... 83.0 85.0 87.0 89.0
    month    (time) int64 1 2 3 4 5 6 7 8 9 10 11 ... 6 7 8 9 10 11 12 1 2 3 4

In [6]:
Nino34 = ssta.loc[:,-5:5,190:240].mean(axis=(1,2))

In [7]:
re0 = Uti.lingReg(ssta,Nino34)

In [9]:
re1 = Uti.Lin_reg(np.array(Nino34),np.array(ssta))

1828
(1828, 16200)


In [19]:
np.array(ssta).shape,np.array(Nino34).shape

((1828, 90, 180), (1828,))

In [11]:
re0[0]

<xarray.DataArray 'sst' (lat: 90, lon: 180)>
array([[        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       ...,
       [19.18127218, 14.40619581,  7.97424209, ..., 11.30591397,
        16.50489323, 25.1930248 ],
       [-2.54418214,  2.44367268,  3.5579471 , ...,  0.25832626,
         2.21513405,  3.68913507],
       [-7.72479857, -3.18259744, -3.76463907, ..., -8.96713691,
        -7.31154209, -9.28882157]])
Coordinates:
  * lon      (lon) float64 0.0 2.0 4.0 6.0 8.0 ... 350.0 352.0 354.0 356.0 358.0
  * lat      (lat) float64 -89.0 -87.0 -85.0 -83.0 -81.0 ... 83.0 85.0 87.0 89.0

In [12]:
re1.slope

array([[       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       ...,
       [19.18127  , 14.406194 ,  7.97424  , ..., 11.305913 , 16.5049   ,
        25.193018 ],
       [-2.544181 ,  2.4436722,  3.5579455, ...,  0.2583256,  2.215133 ,
         3.689136 ],
       [-7.7247977, -3.182597 , -3.764638 , ..., -8.967135 , -7.311541 ,
        -9.288822 ]], dtype=float32)

In [13]:
import pymzl

In [ ]:
pymzl.Lin_reg